# Generated by Django 5.0 on 2023-12-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('brand', models.CharField(max_length=256)),
                ('start_bid', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='myapp/images')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
